# Generated by Django 3.1.2 on 2020-10-10 22:48

from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, storage=profiles.models.UploadStorage(), upload_to=profiles.models.upload_to, verbose_name='头像')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='个人简介')),
                ('email_verified', models.BooleanField(default=False, verbose_name='电子信箱验证')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='所在学校')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='通讯地址')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='城市')),
                ('province', models.CharField(blank=True, choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], db_index=True, max_length=12, verbose_name='省份')),
                ('post_code', models.CharField(blank=True, max_length=7, verbose_name='邮编')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
